// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWheB12-Ox4n8oJy5vnZpe7p0GWlfJ7zY',
    appId: '1:521025592506:web:987669a499558dc5f23683',
    messagingSenderId: '521025592506',
    projectId: 'flutter-chat-app-mrk',
    authDomain: 'flutter-chat-app-mrk.firebaseapp.com',
    storageBucket: 'flutter-chat-app-mrk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYen7uSs4RKOssvt6qGGoU62p1ul4vGX4',
    appId: '1:521025592506:android:606ae8b10a311dd3f23683',
    messagingSenderId: '521025592506',
    projectId: 'flutter-chat-app-mrk',
    storageBucket: 'flutter-chat-app-mrk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1OkVGKTio6y0VqGu70uzw0vDcz7UNDzk',
    appId: '1:521025592506:ios:f4ae86d7b8a6f524f23683',
    messagingSenderId: '521025592506',
    projectId: 'flutter-chat-app-mrk',
    storageBucket: 'flutter-chat-app-mrk.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1OkVGKTio6y0VqGu70uzw0vDcz7UNDzk',
    appId: '1:521025592506:ios:f4ae86d7b8a6f524f23683',
    messagingSenderId: '521025592506',
    projectId: 'flutter-chat-app-mrk',
    storageBucket: 'flutter-chat-app-mrk.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWheB12-Ox4n8oJy5vnZpe7p0GWlfJ7zY',
    appId: '1:521025592506:web:cf03d75c6fb8273cf23683',
    messagingSenderId: '521025592506',
    projectId: 'flutter-chat-app-mrk',
    authDomain: 'flutter-chat-app-mrk.firebaseapp.com',
    storageBucket: 'flutter-chat-app-mrk.firebasestorage.app',
  );
}